project_id = "tyrzadrrllefxwquixir"

[functions.cosmic-synthesis]
verify_jwt = false

[functions.calculate-natal-chart]
verify_jwt = false

[functions.cosmic-mentor]
verify_jwt = false

[functions.karmic-match]
verify_jwt = false

[functions.karmic-analysis]
verify_jwt = false
