project_id = "nyauiqglwkxrxkkvjvxr"

[functions.cosmic-synthesis]
verify_jwt = false

[functions.calculate-natal-chart]
verify_jwt = false

[functions.cosmic-mentor]
verify_jwt = false

[functions.karmic-match]
verify_jwt = false

[functions.karmic-analysis]
verify_jwt = false

[functions.cosmic-letter]
verify_jwt = false

[functions.aspect-interpreter]
verify_jwt = false

[functions.planet-interpreter]
verify_jwt = false
